version: "3.9"
services:
  app:
    container_name: application
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    ports: 
      - "8081:8081" 
    depends_on:
      - postgres-db  
    links:
      - postgresdb
    volumes:
      - app:/lifesaver_app
    environment:
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME} 
      POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT} 
      POSTGRES_DB_USER: ${POSTGRES_DB_USER} 
      POSTGRES_DB_PASS: ${POSTGRES_DB_PASS}
    network_mode: host
  postgresdb:
    image: postgres:latest
    container_name: databasse
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME} 
      POSTGRES_USER: ${POSTGRES_DB_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
    network_mode: host
  flyway:
    image: flyway/flyway:latest
    environment:
         - FLYWAY_USER=${POSTGRES_DB_USER}
         - FLYWAY_PASSWORD=${POSTGRES_DB_PASS}
         - FLYWAY_URL=jdbc:postgresql://postgres:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
    command: -locations=filesystem:/sql/flyway -connectRetries=60 migrate
    volumes:
      - ${PWD}/sql_versions:/flyway/sql
      - ${PWD}/docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgresdb

volumes:
  app:
  database_postgres:




















# INITIAL ATTEMPT

# version: '3'
# services:
#   app:
#     container_name: full_app
#     build: .
#     ports: 
#       - 8080:8080 
#     restart: on-failure
#     volumes:
#       - api:/usr/src/app/
#     depends_on:
#       - fullstack-postgres
#     networks:
#       - fullstack

#   fullstack-postgres:
#     image: postgres:latest
#     restart: always
#     container_name: full_db_postgres
#     environment:
#       - POSTGRES_USER=${DB_USER}  
#       - POSTGRES_PASSWORD=${DB_PASSWORD}
#       - POSTGRES_DB=${DB_NAME}
#       - DATABASE_HOST=${DB_HOST} 
#     ports:
#       - '5432:5432'
#     volumes:
#       - database_postgres:/var/lib/postgresql/data
#     networks:
#       - fullstack

# volumes:
#   api:
#   database_postgres:

# # Networks to be created to facilitate communication between containers
# networks:
#   fullstack:
#     driver: bridge









